In [42]:
import numpy as np

# Use the following code for the questions below:

In [43]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])
a

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

## 1. How many negative numbers are there?



In [44]:
a_negative = a < 0

count_negative_in_a = a_negative.sum()
count_negative_in_a

4

## 2. How many positive numbers are there?



In [45]:
a_positive = a > 0

count_positive_in_a = a_positive.sum()
count_positive_in_a

5

## 3. How many even positive numbers are there?



In [46]:
even_positive_in_a = a[a_positive] % 2 == 0
count_even_positive_in_a = even_positive_in_a.sum()
count_even_positive_in_a

3

## 4. If you were to add 3 to each data point, how many positive numbers would there be?



In [47]:
a_add_3_positive = (a + 3) > 0

count_add_3_positive = a_add_3_positive.sum()
count_add_3_positive

10

## 5. If you squared each number, what would the new mean and standard deviation be?



In [48]:
a_squared = a ** 2

print(f"The mean of a^2 is {a_squared.mean()}") # 74.0
print(f"The standard deviation of a^2 is {a_squared.std()}") # 144.0243035046516

The mean of a^2 is 74.0
The standard deviation of a^2 is 144.0243035046516


## 6. A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set. See this link for more on centering.


In [49]:
a_centered = a - a.mean()
print(f"'a' centered is {a_centered}")


'a' centered is [  1.   7.   9.  20.  -5.  -4.  -3.  -3.  -3.  -9.   0. -10.]


## 7. Calculate the z-score for each data point. Recall that the z-score is given by:
#              Z = ((x-μ)/σ)



In [10]:
z_score = (a - a.mean()) / a.std()

print(f"The z score of each data point is {z_score}")
print(f"Check z score accuracy: mean should be 0: {z_score.mean()} and std should be 1: {z_score.std()}")

The z score of each data point is [ 0.12403473  0.86824314  1.11631261  2.48069469 -0.62017367 -0.49613894
 -0.3721042  -0.3721042  -0.3721042  -1.11631261  0.         -1.24034735]
Check z score accuracy: mean should be 0: 3.700743415417188e-17 and std should be 1: 1.0


## 8. Copy the setup and exercise directions from More Numpy Practice into your numpy_exercises.py and add your solutions.


In [50]:
import numpy as np
# Life w/o numpy to life with numpy

## Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Use python's built in functionality/operators to determine the following:
# Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list
sum_of_a = np.sum(a)
print(f'Exercise 1 Answer: sum_of_a = {sum_of_a}')
# Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list
min_of_a = np.min(a)
print(f'Exercise 2 Answer: min_of_a = {min_of_a}')
# Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list
max_of_a = np.max(a)
print(f'Exercise 3 Answer: max_of_a = {max_of_a}')
# Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list
mean_of_a = np.mean(a)
print(f'Exercise 4 Answer: mean_of_a = {mean_of_a}')
# Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in 
# the above list together
product_of_a = np.prod(a)
print(f'Exercise 5 Answer: product_of_a = {product_of_a}')
# Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]
squares_of_a = np.square(a)
print(f'Exercise 6 Answer: squares_of_a = {squares_of_a}')
# Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers
odds_in_a = []
for num in a:
    if num % 2 != 0:
        odds_in_a.append(num)
count_odds_in_a = len(odds_in_a)
print(f'Exercise 7 Answer: odds_in_a = {odds_in_a}')
# Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.
evens_in_a = []
for num in a:
    if num % 2 == 0:
        evens_in_a.append(num)
count_evens_in_a = len(evens_in_a)

print(f'Exercise 8 Answer: evens_in_a = {evens_in_a}')

Exercise 1 Answer: sum_of_a = 55
Exercise 2 Answer: min_of_a = 1
Exercise 3 Answer: max_of_a = 10
Exercise 4 Answer: mean_of_a = 5.5
Exercise 5 Answer: product_of_a = 3628800
Exercise 6 Answer: squares_of_a = [  1   4   9  16  25  36  49  64  81 100]
Exercise 7 Answer: odds_in_a = [1, 3, 5, 7, 9]
Exercise 8 Answer: evens_in_a = [2, 4, 6, 8, 10]


array([[3, 4, 5],
       [6, 7, 8]])

In [62]:
## What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...
## Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.
b = [
    [3, 4, 5],
    [6, 7, 8]
]

b_array = np.array(b)
b_array
# Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**
sum_of_b = 0
for row in b:
    sum_of_b += sum(row)
sum_of_b_array = b_array.sum()
print(f'Exercise 1:\n{sum_of_b_array}')
# sum_of_b = b.sum()
# sum_of_b
# Exercise 2 - refactor the following to use numpy. 
min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])  
min_of_b_array = b_array.min()
print(f'Exercise 2:\n{min_of_b_array}')
# Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])
max_of_b_array = b_array.max()
print(f'Exercise 3:\n{max_of_b_array}')
# Exercise 4 - refactor the following using numpy to find the mean of b
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))
mean_of_b_array = b_array.mean()
print(f'Exercise 4:\n{mean_of_b_array}')
# Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number
product_of_b_array = b_array.prod()
print(f'Exercise 5:\n{product_of_b_array}')
# Exercise 6 - refactor the following to use numpy to find the list of squares 
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)
squares_of_b_array = np.square(a)
print(f'Exercise 6:\n{squares_of_b_array}')
# Exercise 7 - refactor using numpy to determine the odds_in_b
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)
odds_in_b_array = b_array[b_array % 2 == 1]
print(f'Exercise 7:\n{odds_in_b_array}')
# Exercise 8 - refactor the following to use numpy to filter only the even numbers
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)
evens_in_b_array = b_array[b_array % 2 == 0]
print(f'Exercise 8:\n{evens_in_b_array}')
# Exercise 9 - print out the shape of the array b.
print(f'Exercise 9:\n{np.shape(b_array)}')
# Exercise 10 - transpose the array b.
trans_b_array = b_array.transpose()
print(f'Exercise 10:\n{trans_b_array}')
# Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)
reshape_b_array_1x6 = b_array.reshape((1,6))
print(f'Exercise 11:\n{reshape_b_array_1x6}')
# Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)
reshape_b_array_6x1 = b_array.reshape((6,1))
print(f'Exercise 12:\n{reshape_b_array_6x1}')

Exercise 1:
33
Exercise 2:
3
Exercise 3:
8
Exercise 4:
5.5
Exercise 5:
20160
Exercise 6:
[  1   4   9  16  25  36  49  64  81 100]
Exercise 7:
[3 5 7]
Exercise 8:
[4 6 8]
Exercise 9:
(2, 3)
Exercise 10:
[[3 6]
 [4 7]
 [5 8]]
Exercise 11:
[[3 4 5 6 7 8]]
Exercise 12:
[[3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [74]:
## Setup 3
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
c_array = np.array(c)
c = c_array 
# HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.
# Exercise 1 - Find the min, max, sum, and product of c.
min_c = c.min()
print(f'Exercise 1:\nmin = {min_c}')

max_c = c.max()
print(f'max = {max_c}')

sum_c = c.sum()
print(f'sum = {sum_c}')

product_c = c.prod()
print(f'product = {product_c}')

# Exercise 2 - Determine the standard deviation of c.
std_c = c.std()
print(f'Exercise 2:\nStdDv = {std_c}')
# Exercise 3 - Determine the variance of c.
var_c = c.var()
print(f'Exercise 3:\nvariance = {var_c}')
# Exercise 4 - Print out the shape of the array c
print(f'Exercise 4:\nshape = {np.shape(c)}')
# Exercise 5 - Transpose c and print out transposed result.
trans_c = c.transpose() # c.T also works
print(f'Exercise 5: transpose =\n {trans_c}')
# Exercise 6 - Get the dot product of the array c with c. 
dot_prod_c = c.dot(c)
print(f'Exercise 6: dot product =\n {dot_prod_c}')
# Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261
sum_of_c_times_trans_c = (c * trans_c).sum()
#print(f'Exercise 7: c=\n {c}\ntrans_c: \n {trans_c}')
#print(f'{c * trans_c}')
print(f'Exercise 7: {sum_of_c_times_trans_c}')
# Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.
prod_of_c_times_trans_c = (c * trans_c).prod()
print(f'Exercise 8: {prod_of_c_times_trans_c}')

Exercise 1:
min = 1
max = 9
sum = 45
product = 362880
Exercise 2:
StdDv = 2.581988897471611
Exercise 3:
variance = 6.666666666666667
Exercise 4:
shape = (3, 3)
Exercise 5: transpose =
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
Exercise 6: dot product =
 [[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
Exercise 7: 261
Exercise 8: 131681894400


In [83]:
## Setup 4
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]

d = np.array(d)
# Exercise 1 - Find the sine of all the numbers in d
sine_d = np.sin(d)
print(f'Exercise 1 (sine):\n{sine_d}')

# Exercise 2 - Find the cosine of all the numbers in d
cos_d = np.cos(d)
print(f'Exercise 2 (cosine):\n{cos_d}')

# Exercise 3 - Find the tangent of all the numbers in d
tan_d = np.tan(d)
print(f'Exercise 3 (tangent):\n{tan_d}')

# Exercise 4 - Find all the negative numbers in d
all_negs_d = d[(d < 0)]
print(f'Exercise 4 (negative numbers):\n{all_negs_d}')

# Exercise 5 - Find all the positive numbers in d
all_pos_d = d[(d > 0)]
print(f'Exercise 5 (positive numbers):\n{all_pos_d}')

# Exercise 6 - Return an array of only the unique numbers in d.
unique_val_d = np.unique(d)
print(f'Exercise 6 (np.unique(d)):\n{unique_val_d}')

# Exercise 7 - Determine how many unique numbers there are in d.
num_unique_d = unique_val_d.size
print(f'Exercise 7 (unique numbers):\n{num_unique_d}')

# Exercise 8 - Print out the shape of d.
print(f'Exercise 8 (shape):\n{d.shape}')

# Exercise 9 - Transpose and then print out the shape of d.
print(f'Exercise 9 (Transpose):\n{d.T}')
print(f'shape of d: {d.T.shape}')
# Exercise 10 - Reshape d into an array of 9 x 2
d_9x2 = d.reshape((9,2))
print(f'Exercise 10 (Reshape):\n{d_9x2}')

Exercise 1 (sine):
[[ 0.89399666 -0.98803162  0.85090352  0.          0.58061118 -0.80115264]
 [ 0.85090352 -0.89399666  0.98803162 -0.17604595  0.89399666  0.        ]
 [-0.30481062  0.85090352 -0.85090352  0.89399666 -0.85090352 -0.80115264]]
Exercise 2 (cosine):
[[-0.44807362  0.15425145  0.52532199  1.          0.81418097 -0.59846007]
 [ 0.52532199 -0.44807362  0.15425145  0.98438195 -0.44807362  1.        ]
 [-0.95241298  0.52532199  0.52532199 -0.44807362  0.52532199 -0.59846007]]
Exercise 3 (tangent):
[[-1.99520041 -6.4053312   1.61977519  0.          0.71312301  1.33869021]
 [ 1.61977519  1.99520041  6.4053312  -0.17883906 -1.99520041  0.        ]
 [ 0.32004039  1.61977519 -1.61977519 -1.99520041 -1.61977519  1.33869021]]
Exercise 4 (negative numbers):
[-90 -30 -45 -45]
Exercise 5 (positive numbers):
[ 90  30  45 120 180  45 270  90  60  45  90 180]
Exercise 6 (np.unique(d)):
[-90 -45 -30   0  30  45  60  90 120 180 270]
Exercise 7 (unique numbers):
11
Exercise 8 (shape):
(3, 6